export const todaysParlay1 = ['Saturday', 'March 14, 2026'];

export const todaysParlay2 = [
  'Saturday',
  'March 14, 2026',
  'San Antonio Spurs',
  '230.5',
  'over_under',
  'False',
];

export const todaysParlay3 = [
  'Saturday',
  'March 14, 2026',
  'Sacramento Kings',
  '231.5',
  'over_under',
  'False',
  'San Antonio Spurs',
  '230.5',
  'over_under',
  'False',
  'Washington Wizards',
  '230.5',
  'over_under',
  'False',
  'Los Angeles Lakers',
  '+130',
  'money_line',
  'True',
  'Atlanta Hawks',
  '-9.5',
  'spread',
  'True',
  'Atlanta Hawks',
  '−355',
  'money_line',
  'True',
  'Boston Celtics',
  '−2400',
  'money_line',
  'True',
  'Los Angeles Clippers',
  '-900',
  'money_line',
  'True',
];
