export const todaysParlay1 = [
  'Friday',
  'April 10, 2026',
  'New York Knicks','221.5','over_under','False',
  'Charlotte Hornets','225.5','over_under','False',
  'Detroit Pistons','+5.5','spread','True',
  'Boston Celtics','226.5','over_under','False',
  'San Antonio Spurs','238.5','over_under','False',
  'San Antonio Spurs','−2100','money_line','True',
  'Brooklyn Nets','+10.5','spread','True',
  'Orlando Magic','−1200','money_line','True',
  'Sacramento Kings','+11.5','spread','True',
  'Sacramento Kings','+390','money_line','True',
];

export const todaysParlay2 = [
  'Friday',
  'April 10, 2026',
  'Charlotte Hornets','225.5','over_under','False',
  'Detroit Pistons','+5.5','spread','True',
  'Chicago Bulls','+15.5','spread','True',
  'Orlando Magic','−1200','money_line','True',
  'Sacramento Kings','+11.5','spread','True',
  'Sacramento Kings','+390','money_line','True',
];

export const todaysParlay3 = [
  'Friday',
  'April 10, 2026',
  'New York Knicks','221.5','over_under','False',
  'Toronto Raptors','+6.5','spread','True',
  'Charlotte Hornets','225.5','over_under','False',
  'Detroit Pistons','+5.5','spread','True',
  'Washington Wizards','243.5','over_under','False',
  'Miami Heat','−1600','money_line','True',
  'Boston Celtics','226.5','over_under','False',
  'Indiana Pacers','+15.5','spread','True',
  'Philadelphia 76ers','−1200','money_line','True',
  'San Antonio Spurs','238.5','over_under','False',
  'San Antonio Spurs','−2100','money_line','True',
  'Chicago Bulls','+15.5','spread','True',
  'Brooklyn Nets','+10.5','spread','True',
  'Orlando Magic','−1200','money_line','True',
  'Memphis Grizzlies','+3.5','spread','True',
  'Sacramento Kings','+11.5','spread','True',
  'Sacramento Kings','+390','money_line','True',
  'Los Angeles Lakers','+114','money_line','True',
];
