// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/carousel/styles.css';
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from '@mantine/core';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/next';
import './globals.css';
import { Header } from './components/Header';
import AutoSignOut from './components/AutoSignOut';

export const metadata = {
  title: 'Integral Information',
  description: 'Generated By Integral Information',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <script src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2'></script>
      </head>
      <body>
        <MantineProvider>
          <Header />
          {children}
          {/* <AutoSignOut /> */}
          <SpeedInsights />
          <Analytics />
        </MantineProvider>
      </body>
    </html>
  );
}
